# Generated by Django 4.2 on 2026-04-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='department_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='Подразделение (EN)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='location_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='Локация (EN)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements_en',
            field=models.TextField(blank=True, help_text='Укажите каждый пункт с новой строки.', verbose_name='Требования (EN)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='summary_en',
            field=models.TextField(blank=True, verbose_name='Краткое описание (EN)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название вакансии (EN)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='department',
            field=models.CharField(max_length=160, verbose_name='Подразделение (RU)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='location',
            field=models.CharField(blank=True, max_length=160, verbose_name='Локация (RU)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(help_text='Укажите каждый пункт с новой строки.', verbose_name='Требования (RU)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='summary',
            field=models.TextField(verbose_name='Краткое описание (RU)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название вакансии (RU)'),
        ),
    ]
